import { Octokit } from '@octokit/rest';
import type { ScoreResult, RiskBand } from './scorer';
import type { NotificationResults } from './notifications/index';
import type { Suggestion } from './ai/prompt';

const MARKER = '<!-- pr-risk-scorer-v2 -->';
const AI_MARKER = '<!-- pr-risk-scorer-ai -->';

const SIGNAL_LABELS: Record<string, string> = {
  filesChanged: 'Diff Size',
  complexityDelta: 'Complexity',
  coverageRatio: 'Coverage Gap',
  migrationFiles: 'Migrations',
  deadCode: 'Dead Code',
  secret_leak: 'Secret Leak',
  bundle_size_delta: 'Bundle Size',
  api_breaking_changes: 'API Breaking',
};

function badge(band: RiskBand): string {
  if (band === 'low') return '🟢 LOW';
  if (band === 'medium') return '🟡 MEDIUM';
  if (band === 'critical') return '🚨 CRITICAL';
  return '🔴 HIGH';
}

function signalBand(score: number): RiskBand {
  if (score < 40) return 'low';
  if (score <= 70) return 'medium';
  return 'high';
}

function buildFooter(notifs: NotificationResults): string {
  const parts: string[] = [];
  if (notifs.slack) parts.push('Slack ✓');
  if (notifs.jira !== null) parts.push(`Jira: ${notifs.jira}`);
  if (notifs.linear) parts.push('Linear ✓');
  return parts.length > 0 ? `Notified: ${parts.join(' | ')}` : '';
}

function buildBody(result: ScoreResult, threshold: number, notifs?: NotificationResults): string {
  const status = result.total <= threshold ? '✅ PASS' : '❌ FAIL';
  const rows = result.signals
    .map(s => {
      const label = `${SIGNAL_LABELS[s.name] ?? s.name} (${Math.round(s.weight)}%)`;
      return `| ${label} | ${s.score.toFixed(1)} | ${badge(signalBand(s.score))} |`;
    })
    .join('\n');

  const lines = [
    MARKER,
    `## PR Risk Score: ${badge(result.band)} (${result.total} / 100)`,
    '',
    `> Threshold: **${threshold}** &nbsp;|&nbsp; Status: ${status}`,
    '',
    '| Analyzer | Score | Risk |',
    '|----------|------:|------|',
    rows,
    '',
    '<details>',
    '<summary>How scores are calculated</summary>',
    '',
    '| Dimension | Weight | Method |',
    '|-----------|--------|--------|',
    '| Diff Size | 20% | Lines added + deleted, capped at 1 000 |',
    '| Complexity | 30% | Average cyclomatic complexity via [lizard](https://github.com/terryyin/lizard) |',
    '| Coverage Gap | 20% | `1 − line_rate` from coverage.xml or lcov.info |',
    '| Dead Code | 15% | Unused exports via [ts-prune](https://github.com/nadeesha/ts-prune), capped at 20 |',
    '| Migrations | 15% | DB migration files detected (0 → 0, 1 → 60, 2 → 80, 3+ → 100) |',
    '',
    '</details>',
    '',
    '*Generated by [pr-risk-scorer](https://github.com/FasterApiWeb/pr-risk-scorer)*',
  ];

  if (result.override === 'secret_leak') {
    lines.push('');
    lines.push('⛔ Merge blocked: credentials detected in diff.');
  }

  if (notifs !== undefined) {
    const footer = buildFooter(notifs);
    if (footer) {
      lines.push('');
      lines.push(footer);
    }
  }

  return lines.join('\n');
}

function buildAiBody(suggestions: Suggestion[]): string {
  const rows = suggestions
    .map((s, i) => {
      const effort = s.effort.charAt(0).toUpperCase() + s.effort.slice(1);
      return `| ${i + 1} | ${s.signal} | ${s.action} | ${effort} |`;
    })
    .join('\n');

  return [
    AI_MARKER,
    '## 🤖 Risk Reduction Suggestions',
    '| # | Signal | Suggested Action | Effort |',
    '|---|--------|-----------------|--------|',
    rows,
    '_Generated by pr-risk-scorer v2_',
  ].join('\n');
}

export async function postComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  result: ScoreResult,
  threshold = 70,
  notifs?: NotificationResults,
  suggestions?: Suggestion[] | null,
): Promise<void> {
  const body = buildBody(result, threshold, notifs);

  const comments = await octokit.paginate(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number: prNumber,
  });

  const existing = comments.find(c => c.body?.includes(MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }

  // secretLeak override: skip AI comment entirely
  if (result.override === 'secret_leak') return;

  const existingAi = comments.find(c => c.body?.includes(AI_MARKER));

  if (suggestions == null || suggestions.length === 0) {
    if (existingAi) {
      await octokit.rest.issues.deleteComment({
        owner,
        repo,
        comment_id: existingAi.id,
      });
    }
    return;
  }

  const aiBody = buildAiBody(suggestions);

  if (existingAi) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingAi.id,
      body: aiBody,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: aiBody,
    });
  }
}
