import { Octokit } from '@octokit/rest';
import type { ScoreResult, RiskBand } from './scorer';

const MARKER = '<!-- pr-risk-scorer -->';

const SIGNAL_LABELS: Record<string, string> = {
  filesChanged: 'Diff Size',
  complexityDelta: 'Complexity',
  coverageRatio: 'Coverage Gap',
  migrationFiles: 'Migrations',
  deadCode: 'Dead Code',
};

function badge(band: RiskBand): string {
  if (band === 'LOW') return '🟢 LOW';
  if (band === 'MEDIUM') return '🟡 MEDIUM';
  return '🔴 HIGH';
}

function signalBand(score: number): RiskBand {
  if (score < 40) return 'LOW';
  if (score <= 70) return 'MEDIUM';
  return 'HIGH';
}

function buildBody(result: ScoreResult, threshold: number): string {
  const status = result.total <= threshold ? '✅ PASS' : '❌ FAIL';
  const rows = result.signals
    .map(s => {
      const label = `${SIGNAL_LABELS[s.name] ?? s.name} (${Math.round(s.weight * 100)}%)`;
      return `| ${label} | ${s.score.toFixed(1)} | ${badge(signalBand(s.score))} |`;
    })
    .join('\n');

  return [
    MARKER,
    `## PR Risk Score: ${badge(result.band)} (${result.total} / 100)`,
    '',
    `> Threshold: **${threshold}** &nbsp;|&nbsp; Status: ${status}`,
    '',
    '| Analyzer | Score | Risk |',
    '|----------|------:|------|',
    rows,
    '',
    '<details>',
    '<summary>How scores are calculated</summary>',
    '',
    '| Dimension | Weight | Method |',
    '|-----------|--------|--------|',
    '| Diff Size | 20% | Lines added + deleted, capped at 1 000 |',
    '| Complexity | 30% | Average cyclomatic complexity via [lizard](https://github.com/terryyin/lizard) |',
    '| Coverage Gap | 20% | `1 − line_rate` from coverage.xml or lcov.info |',
    '| Dead Code | 15% | Unused exports via [ts-prune](https://github.com/nadeesha/ts-prune), capped at 20 |',
    '| Migrations | 15% | DB migration files detected (0 → 0, 1 → 60, 2 → 80, 3+ → 100) |',
    '',
    '</details>',
    '',
    '*Generated by [pr-risk-scorer](https://github.com/FasterApiWeb/pr-risk-scorer)*',
  ].join('\n');
}

export async function postComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  result: ScoreResult,
  threshold = 70,
): Promise<void> {
  const body = buildBody(result, threshold);

  const comments = await octokit.paginate(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number: prNumber,
  });

  const existing = comments.find(c => c.body?.includes(MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }
}
