from __future__ import annotations

import json
import urllib.error
import urllib.request

_ANALYZER_LABELS: dict[str, str] = {
    "diff_size": "Diff Size (20%)",
    "complexity": "Complexity (30%)",
    "coverage": "Coverage Gap (20%)",
    "dead_code": "Dead Code (15%)",
    "migration": "Migrations (15%)",
}

_GITHUB_API = "https://api.github.com"


def _risk_badge(score: float) -> str:
    if score < 40:
        return "🟢 LOW"
    elif score <= 70:
        return "🟡 MEDIUM"
    return "🔴 HIGH"


class Reporter:
    def __init__(self, github_token: str, repository: str, pr_number: int) -> None:
        self.github_token = github_token
        self.repository = repository
        self.pr_number = pr_number

    def post_comment(
        self,
        total_score: float,
        scores: dict[str, float],
        threshold: float,
    ) -> None:
        body = self._build_comment(total_score, scores, threshold)
        url = f"{_GITHUB_API}/repos/{self.repository}/issues/{self.pr_number}/comments"
        payload = json.dumps({"body": body}).encode()
        req = urllib.request.Request(
            url,
            data=payload,
            headers={
                "Authorization": f"Bearer {self.github_token}",
                "Accept": "application/vnd.github+json",
                "Content-Type": "application/json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                if resp.status not in (200, 201):
                    raise RuntimeError(f"Unexpected GitHub API status: {resp.status}")
        except urllib.error.HTTPError as exc:
            raise RuntimeError(f"GitHub API error {exc.code}: {exc.read().decode()}") from exc

    def _build_comment(
        self,
        total_score: float,
        scores: dict[str, float],
        threshold: float,
    ) -> str:
        badge = _risk_badge(total_score)
        status = "✅ PASS" if total_score <= threshold else "❌ FAIL"
        table_rows = "\n".join(
            f"| {label} | {scores.get(key, 0.0):.1f} | {_risk_badge(scores.get(key, 0.0))} |"
            for key, label in _ANALYZER_LABELS.items()
        )
        return f"""\
## PR Risk Score: {badge} ({total_score:.1f} / 100)

> Threshold: **{threshold:.0f}** &nbsp;|&nbsp; Status: {status}

| Analyzer | Score | Risk |
|----------|------:|------|
{table_rows}

<details>
<summary>How scores are calculated</summary>

| Dimension | Weight | Method |
|-----------|--------|--------|
| Diff Size | 20% | Lines added + deleted, capped at 1 000 |
| Complexity | 30% | Average cyclomatic complexity via [radon](https://radon.readthedocs.io/) |
| Coverage Gap | 20% | `1 − line_rate` from coverage.xml |
| Dead Code | 15% | Unused symbol count via [vulture](https://github.com/jendrikseipp/vulture), capped at 20 |
| Migrations | 15% | Presence of DB migration files (tiered: 0 → 0, 1 → 60, 2 → 80, 3+ → 100) |

</details>

*Generated by [pr-risk-scorer](https://github.com/FasterApiWeb/pr-risk-scorer)*"""
